[firewall_alias]
24.7

[firewall_rules]
24.7

[interfaces_assignments]
24.7
25.1
25.7
26.1

[opnsense_config]
24.7
25.1
25.7
26.1

[system_access_users]
24.7

[system_high_availability_settings]
24.7
25.1

[system_settings_general]
24.7
25.1
25.7
26.1

[system_settings_logging]
24.7

[opnsense:children]
firewall_alias
firewall_rules
interfaces_assignments
opnsense_config
system_access_users
system_high_availability_settings
system_settings_general
system_settings_logging
