[interfaces_assignments]
25.1
25.7
26.1

[opnsense_config]
25.1
25.7
26.1
26.7

[system_high_availability_settings]
25.1

[system_settings_general]
25.1
25.7
26.1
26.7

[opnsense:children]
interfaces_assignments
opnsense_config
system_high_availability_settings
system_settings_general
