# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: puzzle
name: opnsense
version: 1.1.1
readme: README.md
authors:
  - Lukas Grimm (github.com/ombre8)
  - Fabio Bertagna (github.com/dongiovanni83)
  - Philipp Matti (github.com/acteru)
  - Reto Kupferschmid (github.com/rekup)
  - Kilian Soltermann (github.com/killuuuhh)
description: Ansible collection for OPNsense
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - opnsense
repository: https://github.com/puzzle/puzzle.opnsense/
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://puzzle.github.io/puzzle.opnsense/collections/puzzle/opnsense/
issues: https://github.com/puzzle/puzzle.opnsense/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - .github
  - changelogs/.plugin-cache.yaml
  - codecov.yml
  - Makefile
  - Pipfile*
  - "*.tar.gz"
  - renovate.json
  - .pylint.rc
  - ansible.cfg
  - .idea
