---
scenario:
    name: system_settings_logging
    test_sequence:
        # - dependency not relevant unless we have requirements
        - destroy
        - syntax
        - create
        - converge
        - idempotence
        - verify
        - destroy

driver:
    name: vagrant
    parallel: true

platforms:
    - name: "23.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "23.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "24.1"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.1"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "24.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
        - 'vm.guest = :freebsd'
        - 'ssh.sudo_command = "%c"'
        - 'ssh.shell = "/bin/sh"'
provisioner:
    name: ansible
    env:
        ANSIBLE_VERBOSITY: 3
        ANSIBLE_LIBRARY: "${VIRTUAL_ENV}/lib/python3.11/site-packages/molecule_plugins/vagrant/modules"
verifier:
    name: ansible
    options:
        become: true
