---
# defaults file for opnsense_configure

#
# System variables should be provided in this structure
#
# system:
#   high_availability:
#     disable_preempt:
#     disconnect_dialup_interfaces:
#     synchronize_states:
#     synchronize_interface:
#     sync_compatibility:
#     synchronize_peer_ip:
#     synchronize_config_to_ip:
#     remote_system_username:
#     remote_system_password:
#     services_to_synchronize:
#   settings:
#     general:
#       hostname:
#       domain:
#       timezone:

system:
  settings:
  high_availability:

# Interface related variables:
#
# interfaces:
#   assignments: []
interfaces:
