---
scenario:
    name: opnsense_config
    test_sequence:
        # - dependency not relevant unless we have requirements
        - destroy
        - syntax
        - create
        - converge
        - idempotence
        - verify
        - destroy

driver:
    name: vagrant
    parallel: true

platforms:
    - name: "23.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "23.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "24.1"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.1"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "24.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "25.1"
      box: puzzle/opnsense
      hostname: false
      box_version: "25.1"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "25.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "25.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'

provisioner:
    name: ansible
    env:
        ANSIBLE_VERBOSITY: 3
    inventory:
      links:
        group_vars: "./group_vars/"
        host_vars: "./host_vars/"

verifier:
    name: ansible
    options:
        become: true
