---
scenario:
    name: system_high_availability_settings
    test_sequence:
        # - dependency not relevant uless we have requirements
        - destroy
        - syntax
        - create
        - converge
        - verify
        - destroy

driver:
    name: vagrant
    parallel: true

platforms:
    - name: "23.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "23.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "24.1"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.1"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'

    - name: "24.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "24.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'

    - name: "25.1"
      box: puzzle/opnsense
      hostname: false
      box_version: "25.1"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'
    - name: "25.7"
      box: puzzle/opnsense
      hostname: false
      box_version: "25.7"
      memory: 1024
      cpus: 2
      instance_raw_config_args:
          - 'vm.guest = :freebsd'
          - 'ssh.sudo_command = "%c"'
          - 'ssh.shell = "/bin/sh"'

provisioner:
    name: ansible
    env:
        ANSIBLE_VERBOSITY: 0
verifier:
    name: ansible
    options:
        become: true
