---
scenario:
  name: system_high_availability_settings
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy

ansible:
  playbooks:
    create: ../_resources/create.yml
    destroy: ../_resources/destroy.yml
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/molecule/_inventory/

verifier:
  name: ansible
  options:
    become: true
